import { createHotContext as __vite__createHotContext } from "/@vite/client";import.meta.hot = __vite__createHotContext("/src/pages/Sistema.jsx");import __vite__cjsImport0_react_jsxDevRuntime from "/node_modules/.vite/deps/react_jsx-dev-runtime.js?v=f31a5e49"; const Fragment = __vite__cjsImport0_react_jsxDevRuntime["Fragment"]; const jsxDEV = __vite__cjsImport0_react_jsxDevRuntime["jsxDEV"];import * as RefreshRuntime from "/@react-refresh";
const inWebWorker = typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope;let prevRefreshReg;let prevRefreshSig;if (import.meta.hot && !inWebWorker) {if (!window.$RefreshReg$) {throw new Error("@vitejs/plugin-react can't detect preamble. Something is wrong.");}prevRefreshReg = window.$RefreshReg$;prevRefreshSig = window.$RefreshSig$;window.$RefreshReg$ = RefreshRuntime.getRefreshReg("/home/u354553529/websites/pPNaUZ1QY/public_html/src/pages/Sistema.jsx");window.$RefreshSig$ = RefreshRuntime.createSignatureFunctionForTransform;}
import __vite__cjsImport3_react from "/node_modules/.vite/deps/react.js?v=f31a5e49"; const React = __vite__cjsImport3_react.__esModule ? __vite__cjsImport3_react.default : __vite__cjsImport3_react; const useState = __vite__cjsImport3_react["useState"]; const useEffect = __vite__cjsImport3_react["useEffect"];
import { Helmet } from "/node_modules/.vite/deps/react-helmet.js?v=f31a5e49";
import { motion } from "/node_modules/.vite/deps/framer-motion.js?v=f31a5e49";
import { Button } from "/src/components/ui/button.jsx";
import { Shield, ChartBar, Presentation, Package, FileText, Users, Percent, Settings, LogIn } from "/node_modules/.vite/deps/lucide-react.js?v=f31a5e49";

const cards = [
  { icon: ChartBar, title: "Dashboard do Corretor", desc: "Métricas de vendas, metas e últimas atividades" },
  { icon: Presentation, title: "Apresentação", desc: "Slides interativos e seleção de cotas" },
  { icon: Package, title: "Gestão de Cotas", desc: "Tabela, filtros avançados e reserva de cota" },
  { icon: FileText, title: "Registro de Vendas", desc: "Formulário completo, uploads e fluxo de status" },
  { icon: Users, title: "Histórico & Clientes", desc: "CRUD de clientes, busca, notas e follow-ups" },
  { icon: Percent, title: "Comissões", desc: "Extratos, gráficos e exportação" },
  { icon: Settings, title: "Administração", desc: "Usuários, cotas, aprovações e relatórios" }
]

function Sistema() {
  const [ready, setReady] = useState(false)
  useEffect(() => { setReady(true) }, [])
  return jsxDEV(Fragment, { children: [
    jsxDEV(Helmet, { children: jsxDEV("title", { children: "Sistema de Gestão • Nova Terra Consórcio" }, void 0, false, { fileName: "/home/u354553529/websites/pPNaUZ1QY/public_html/src/pages/Sistema.jsx", lineNumber: 23, columnNumber: 17 }, this) }, void 0, false, { fileName: "/home/u354553529/websites/pPNaUZ1QY/public_html/src/pages/Sistema.jsx", lineNumber: 22, columnNumber: 15 }, this),
    jsxDEV("section", { className: "bg-gradient-to-br from-[#658f4c] to-[#346d47] text-white", children: jsxDEV("div", { className: "max-w-6xl mx-auto px-4 py-12", children: jsxDEV("div", { className: "grid md:grid-cols-2 gap-8 items-center", children: [
      jsxDEV("div", { children: [
        jsxDEV("h1", { className: "text-3xl md:text-4xl font-extrabold mb-3", children: "Sistema de Gestão de Consórcios" }, void 0, false, { fileName: "/home/u354553529/websites/pPNaUZ1QY/public_html/src/pages/Sistema.jsx", lineNumber: 28, columnNumber: 11 }, this),
        jsxDEV("p", { className: "text-white/90", children: "Plataforma para corretores e administração com foco em performance, segurança e usabilidade." }, void 0, false, { fileName: "/home/u354553529/websites/pPNaUZ1QY/public_html/src/pages/Sistema.jsx", lineNumber: 29, columnNumber: 11 }, this),
        jsxDEV("div", { className: "mt-5 flex gap-3", children: [
          jsxDEV(Button, { className: "bg-white text-[#658f4c] hover:bg-gray-100", children: jsxDEV("a", { href: "#login", children: jsxDEV("span", { className: "inline-flex items-center gap-2", children: [jsxDEV(LogIn, { size: 18 }, void 0, false, { fileName: "/home/u354553529/websites/pPNaUZ1QY/public_html/src/pages/Sistema.jsx", lineNumber: 32, columnNumber: 52 }, this), "Entrar" ] }, void 0, true, { fileName: "/home/u354553529/websites/pPNaUZ1QY/public_html/src/pages/Sistema.jsx", lineNumber: 32, columnNumber: 36 }, this) }, void 0, false, { fileName: "/home/u354553529/websites/pPNaUZ1QY/public_html/src/pages/Sistema.jsx", lineNumber: 32, columnNumber: 24 }, this) }, void 0, false, { fileName: "/home/u354553529/websites/pPNaUZ1QY/public_html/src/pages/Sistema.jsx", lineNumber: 32, columnNumber: 11 }, this),
          jsxDEV(Button, { variant: "outline", className: "border-white text-white", children: "Ver funcionalidades" }, void 0, false, { fileName: "/home/u354553529/websites/pPNaUZ1QY/public_html/src/pages/Sistema.jsx", lineNumber: 33, columnNumber: 11 }, this)
        ] }, void 0, true, { fileName: "/home/u354553529/websites/pPNaUZ1QY/public_html/src/pages/Sistema.jsx", lineNumber: 31, columnNumber: 11 }, this)
      ] }, void 0, true, { fileName: "/home/u354553529/websites/pPNaUZ1QY/public_html/src/pages/Sistema.jsx", lineNumber: 27, columnNumber: 9 }, this),
      jsxDEV("div", { className: "hidden md:block", children: jsxDEV(Shield, { size: 84, className: "mx-auto" }, void 0, false, { fileName: "/home/u354553529/websites/pPNaUZ1QY/public_html/src/pages/Sistema.jsx", lineNumber: 37, columnNumber: 11 }, this) }, void 0, false, { fileName: "/home/u354553529/websites/pPNaUZ1QY/public_html/src/pages/Sistema.jsx", lineNumber: 36, columnNumber: 9 }, this)
    ] }, void 0, true, { fileName: "/home/u354553529/websites/pPNaUZ1QY/public_html/src/pages/Sistema.jsx", lineNumber: 26, columnNumber: 7 }, this) }, void 0, false, { fileName: "/home/u354553529/websites/pPNaUZ1QY/public_html/src/pages/Sistema.jsx", lineNumber: 25, columnNumber: 5 }, this) }, void 0, false, { fileName: "/home/u354553529/websites/pPNaUZ1QY/public_html/src/pages/Sistema.jsx", lineNumber: 24, columnNumber: 3 }, this),
    jsxDEV("section", { className: "bg-white", children: jsxDEV("div", { className: "max-w-6xl mx-auto px-4 py-10", children: [
      jsxDEV("h2", { className: "text-2xl font-bold text-[#24352f] mb-6", children: "Módulos" }, void 0, false, { fileName: "/home/u354553529/websites/pPNaUZ1QY/public_html/src/pages/Sistema.jsx", lineNumber: 42, columnNumber: 7 }, this),
      jsxDEV("div", { className: "grid md:grid-cols-3 gap-6", children: cards.map((c, i) => jsxDEV(motion.div, { initial: { opacity: 0, y: 12 }, whileInView: { opacity: 1, y: 0 }, transition: { duration: 0.4, delay: i * 0.05 }, viewport: { once: true }, className: "rounded-xl border p-5", children: [
        jsxDEV("div", { className: "flex items-center gap-3", children: [ jsxDEV(c.icon, { className: "text-[#658f4c]", size: 22 }, void 0, false, { fileName: "/home/u354553529/websites/pPNaUZ1QY/public_html/src/pages/Sistema.jsx", lineNumber: 45, columnNumber: 74 }, this), jsxDEV("h3", { className: "font-semibold text-[#24352f]", children: c.title }, void 0, false, { fileName: "/home/u354553529/websites/pPNaUZ1QY/public_html/src/pages/Sistema.jsx", lineNumber: 45, columnNumber: 112 }, this) ] }, void 0, true, { fileName: "/home/u354553529/websites/pPNaUZ1QY/public_html/src/pages/Sistema.jsx", lineNumber: 45, columnNumber: 11 }, this),
        jsxDEV("p", { className: "text-gray-600 mt-2", children: c.desc }, void 0, false, { fileName: "/home/u354553529/websites/pPNaUZ1QY/public_html/src/pages/Sistema.jsx", lineNumber: 46, columnNumber: 9 }, this),
        jsxDEV("div", { className: "mt-4", children: jsxDEV(Button, { className: "bg-[#658f4c]", children: "Abrir" }, void 0, false, { fileName: "/home/u354553529/websites/pPNaUZ1QY/public_html/src/pages/Sistema.jsx", lineNumber: 47, columnNumber: 11 }, this) }, void 0, false, { fileName: "/home/u354553529/websites/pPNaUZ1QY/public_html/src/pages/Sistema.jsx", lineNumber: 47, columnNumber: 9 }, this)
      ] }, i, true, { fileName: "/home/u354553529/websites/pPNaUZ1QY/public_html/src/pages/Sistema.jsx", lineNumber: 44, columnNumber: 9 }, this)) }, void 0, false, { fileName: "/home/u354553529/websites/pPNaUZ1QY/public_html/src/pages/Sistema.jsx", lineNumber: 43, columnNumber: 7 }, this)
    ] }, void 0, true, { fileName: "/home/u354553529/websites/pPNaUZ1QY/public_html/src/pages/Sistema.jsx", lineNumber: 41, columnNumber: 5 }, this) }, void 0, false, { fileName: "/home/u354553529/websites/pPNaUZ1QY/public_html/src/pages/Sistema.jsx", lineNumber: 40, columnNumber: 3 }, this),
    jsxDEV("section", { id: "login", className: "bg-white", children: jsxDEV("div", { className: "max-w-2xl mx-auto px-4 pb-12", children: [
      jsxDEV("h2", { className: "text-2xl font-bold text-[#24352f] mb-4", children: "Acesso" }, void 0, false, { fileName: "/home/u354553529/websites/pPNaUZ1QY/public_html/src/pages/Sistema.jsx", lineNumber: 52, columnNumber: 7 }, this),
      jsxDEV("div", { className: "rounded-xl border p-5", children: [
        jsxDEV("p", { className: "text-gray-600 mb-4", children: "Entre com seu e-mail e senha para acessar o painel." }, void 0, false, { fileName: "/home/u354553529/websites/pPNaUZ1QY/public_html/src/pages/Sistema.jsx", lineNumber: 54, columnNumber: 9 }, this),
        jsxDEV("form", { className: "grid gap-3", children: [
          jsxDEV("input", { type: "email", placeholder: "E-mail", className: "border rounded px-3 py-2" }, void 0, false, { fileName: "/home/u354553529/websites/pPNaUZ1QY/public_html/src/pages/Sistema.jsx", lineNumber: 56, columnNumber: 11 }, this),
          jsxDEV("input", { type: "password", placeholder: "Senha", className: "border rounded px-3 py-2" }, void 0, false, { fileName: "/home/u354553529/websites/pPNaUZ1QY/public_html/src/pages/Sistema.jsx", lineNumber: 57, columnNumber: 11 }, this),
          jsxDEV(Button, { className: "bg-[#658f4c]", type: "button", children: "Entrar" }, void 0, false, { fileName: "/home/u354553529/websites/pPNaUZ1QY/public_html/src/pages/Sistema.jsx", lineNumber: 58, columnNumber: 11 }, this)
        ] }, void 0, true, { fileName: "/home/u354553529/websites/pPNaUZ1QY/public_html/src/pages/Sistema.jsx", lineNumber: 55, columnNumber: 9 }, this)
      ] }, void 0, true, { fileName: "/home/u354553529/websites/pPNaUZ1QY/public_html/src/pages/Sistema.jsx", lineNumber: 53, columnNumber: 7 }, this)
    ] }, void 0, true, { fileName: "/home/u354553529/websites/pPNaUZ1QY/public_html/src/pages/Sistema.jsx", lineNumber: 51, columnNumber: 5 }, this) }, void 0, false, { fileName: "/home/u354553529/websites/pPNaUZ1QY/public_html/src/pages/Sistema.jsx", lineNumber: 50, columnNumber: 3 }, this)
  ] }, void 0, true, { fileName: "/home/u354553529/websites/pPNaUZ1QY/public_html/src/pages/Sistema.jsx", lineNumber: 21, columnNumber: 3 }, this)
}
_c = Sistema;export default Sistema;var _c;$RefreshReg$(_c, "Sistema");if (import.meta.hot && !inWebWorker) {window.$RefreshReg$ = prevRefreshReg;window.$RefreshSig$ = prevRefreshSig;}if (import.meta.hot && !inWebWorker) {RefreshRuntime.__hmr_import(import.meta.url).then((currentExports) => {RefreshRuntime.registerExportsForReactRefresh("/home/u354553529/websites/pPNaUZ1QY/public_html/src/pages/Sistema.jsx", currentExports);import.meta.hot.accept((nextExports) => {if (!nextExports)return;const invalidateMessage = RefreshRuntime.validateRefreshBoundaryAndEnqueueUpdate("/home/u354553529/websites/pPNaUZ1QY/public_html/src/pages/Sistema.jsx", currentExports, nextExports);if (invalidateMessage)import.meta.hot.invalidate(invalidateMessage);});});}